---
abstract: 'Distribute sized items to buckets with limited size'
author:
  - 'Mike <cpan@perlmeister.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-Bucketizer
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Std: 0
  Pod::Usage: 0
  Sysadm::Install: 0.23
resources:
  repository: http://github.com/mschilli/algorithm-bucketizer-perl.git
version: 0.13
