--- #YAML:1.0
name:                Algorithm-Bucketizer
version:             0.12
abstract:            Distribute sized items to buckets with limited size
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Getopt::Std:                   0
    Pod::Usage:                    0
    Sysadm::Install:               0.23
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike <cpan@perlmeister.com>
